[project]
name = "ps26052-anc"
version = "0.1.0"
description = "AI/ML-enabled Adaptive Noise Cancellation for Defence Communications (DRDO PS26052)"
readme = "README.md"
requires-python = ">=3.9,<3.13"
dependencies = [
    "cython>=3.3.0",
    "deepfilternet>=0.5.6",
    "matplotlib>=3.9.4",
    "numba>=0.60.0",
    "onnx>=1.19.1",
    "onnxruntime>=1.20.1",
    "pandas>=2.3.3",
    "pystoi>=0.4.1",
    "pyyaml>=6.0.3",
    "scipy>=1.13.1",
    "seaborn>=0.13.2",
    "sounddevice>=0.5.6",
    "soundfile>=0.13.1",
    "torch==2.5.1",
    "torchaudio==2.5.1",
    "torchmetrics>=1.8.2",
]

[tool.uv]
package = false
