"""
demo/webdash/record_compare.py — Dashboard "Record & Compare" mode.

The manual, non-live workflow this replaces (what you'd previously run by
hand on the Pi):

    arecord -D plughw:2,0 -f S16_LE -r 48000 -c 1 -d 10 /tmp/demo_input/clip.wav
    python models/deepfilternet/run_inference.py --input-dir /tmp/demo_input --output-dir /tmp/demo_output
    aplay -D plughw:2,0 /tmp/demo_input/clip.wav
    aplay -D plughw:2,0 /tmp/demo_output/clip_DeepFilterNet3.wav

This module does the same thing -- record a short clip from the real mic,
then run it through every method -- behind one button, and serves noisy /
spectral_subtraction / wiener / deepfilternet_tuned side by side (the same
layout as demo/webdash/compare.py's corpus comparison mode).

Honesty note (same principle as the rest of this dashboard): a freshly
recorded clip has NO clean reference, so SI-SNR/STOI/PESQ-WB genuinely cannot
be computed here -- there is nothing to compare against. DNSMOS (SIG/BAK/OVR)
is the one quality metric that doesn't need a reference, so it's the only
number shown; the UI must not fabricate the others.

The oracle "nlms" baseline (baselines/nlms/nlms.py) is deliberately excluded:
it requires a perfectly sample-aligned, isolated noise-only reference signal
that only exists because the offline corpus was generated by mixing two known
files. A live recording has no such isolated noise track, even with a second
microphone (that would be a second noisy capture, not the true noise), so
including "nlms" here would misrepresent an oracle-fed result as a live one.

Self-test (Mode A, no microphone required):
    python demo/webdash/record_compare.py --self-test
    Exercises the processing pipeline on a synthetic clip written to disk
    (register_and_process() takes any existing WAV, not just a live recording)
    -- record_clip() itself (needs real hardware) is not covered.
"""

import argparse
import os
import sys
import time
import uuid

import numpy as np
import soundfile as sf

_REPO_ROOT = os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
if _REPO_ROOT not in sys.path:
    sys.path.insert(0, _REPO_ROOT)

from baselines.spectral_subtraction.spectral_subtraction import spectral_subtraction
from baselines.wiener.wiener import wiener_filter
from models.deepfilternet.run_inference import process_file as _dfn_process_file

try:
    from fastapi import FastAPI, HTTPException
    from fastapi.responses import FileResponse
    _FASTAPI_OK = True
except ImportError:
    _FASTAPI_OK = False

DEFAULT_RECORDINGS_DIR = os.path.join(_REPO_ROOT, "demo", "webdash", "recordings")
METHODS = ("noisy", "spectral_subtraction", "wiener", "deepfilternet_tuned")

# Lazily-loaded DeepFilterNet singleton (avoid a ~200ms model load per clip).
_dfn_model = None
_dfn_state = None


def _get_dfn_model():
    global _dfn_model, _dfn_state
    if _dfn_model is None:
        from models.deepfilternet.df_compat import init_df
        _dfn_model, _dfn_state, _ = init_df(post_filter=False, log_level="ERROR")
    return _dfn_model, _dfn_state


def _score_dnsmos_or_none(path: str):
    """Returns a {sig,bak,ovr,n_windows} dict, or None if DNSMOS is unavailable
    (onnxruntime not installed, the model hasn't been downloaded, or the model
    file present is somehow incompatible -- e.g. a re-pinned upstream commit
    whose weights turn out to expect a different input shape, as happened
    2026-09-05 when the originally-vendored sig_bak_ovr.onnx became
    permanently unreachable upstream and this repo hadn't yet been updated to
    a compatible replacement). Any of these degrade to "unavailable", never a
    fabricated number -- see models/dnsmos/download_model.py."""
    try:
        from models.dnsmos.dnsmos_infer import score_file
        return score_file(path)
    except (ImportError, FileNotFoundError):
        return None
    except Exception as exc:
        print(f"[record_compare] DNSMOS scoring failed for {path!r}: {exc}", file=sys.stderr)
        return None


def record_clip(duration_sec: float, device=None, sr: int = 48000, channels: int = 1) -> np.ndarray:
    """
    Record `duration_sec` seconds from a real microphone. Requires
    sounddevice + working audio hardware -- not exercised by --self-test.
    Returns a (n_samples,) mono float32 array at `sr`.

    Reuses live/pipeline.py's own device-rate resolution (_resolve_device /
    _resolve_stream_samplerate / _resample) rather than assuming the device
    natively supports `sr` -- a headset mic reporting e.g. 44.1 kHz native
    would otherwise raise PortAudioError here exactly like it would in the
    live pipeline if that same guard didn't exist there (see
    live/pipeline.py's _resolve_stream_samplerate docstring).
    """
    import sounddevice as sd
    from live.pipeline import _resolve_device, _resolve_stream_samplerate, _resample

    resolved_device = _resolve_device(device, kind="input")
    stream_sr = _resolve_stream_samplerate(resolved_device, sr, channels, kind="input")

    frames = int(round(duration_sec * stream_sr))
    audio = sd.rec(frames, samplerate=stream_sr, channels=channels, device=resolved_device, dtype="float32")
    sd.wait()
    mono = audio[:, 0] if audio.ndim > 1 else audio
    if stream_sr != sr:
        mono = _resample(mono, stream_sr, sr)
    return mono


def register_and_process(raw_audio_path: str, recordings_dir: str = DEFAULT_RECORDINGS_DIR,
                          atten_lim_db: float = 30.0) -> dict:
    """
    Given an existing WAV file (freshly recorded, or any other source -- this
    is the seam --self-test exercises without real hardware), run every
    method in METHODS and register the outputs for serving. Returns
    {recording_id, methods: {name: {path, dnsmos}}}.
    """
    recording_id = time.strftime("%Y%m%d_%H%M%S_") + uuid.uuid4().hex[:6]
    out_dir = os.path.join(recordings_dir, recording_id)
    os.makedirs(out_dir, exist_ok=True)

    noisy_path = os.path.join(out_dir, "noisy.wav")
    audio, sr = sf.read(raw_audio_path, dtype="float32")
    if audio.ndim > 1:
        audio = audio[:, 0]
    sf.write(noisy_path, audio, sr)

    ss_path = os.path.join(out_dir, "spectral_subtraction.wav")
    sf.write(ss_path, spectral_subtraction(audio, sr=sr), sr)

    wiener_path = os.path.join(out_dir, "wiener.wav")
    sf.write(wiener_path, wiener_filter(audio, sr=sr), sr)

    dfn_path = os.path.join(out_dir, "deepfilternet_tuned.wav")
    model, df_state = _get_dfn_model()
    _dfn_process_file(model, df_state, noisy_path, dfn_path, atten_lim_db=atten_lim_db)

    paths = {
        "noisy": noisy_path,
        "spectral_subtraction": ss_path,
        "wiener": wiener_path,
        "deepfilternet_tuned": dfn_path,
    }
    methods_out = {name: {"path": path, "dnsmos": _score_dnsmos_or_none(path)}
                    for name, path in paths.items()}

    return {
        "recording_id": recording_id,
        "duration_sec": round(len(audio) / sr, 2),
        "methods": methods_out,
    }


def make_record_app(recordings_dir: str = DEFAULT_RECORDINGS_DIR, device=None,
                     sample_rate: int = 48000, atten_lim_db: float = 30.0) -> "FastAPI":
    if not _FASTAPI_OK:
        raise ImportError("fastapi is required. Install: pip install fastapi uvicorn[standard]")

    os.makedirs(recordings_dir, exist_ok=True)
    app = FastAPI(title="PS26052 Record & Compare", docs_url=None, redoc_url=None)
    # In-memory index: recording_id -> {method: path}. Deliberately not
    # persisted -- this is a scratch/demo feature, not the audited corpus.
    _index: dict = {}

    @app.post("/record")
    async def record(duration_sec: float = 10.0):
        if not (1.0 <= duration_sec <= 60.0):
            raise HTTPException(status_code=400, detail="duration_sec must be between 1 and 60")
        raw = record_clip(duration_sec, device=device, sr=sample_rate, channels=1)
        tmp_path = os.path.join(recordings_dir, "_tmp_capture.wav")
        sf.write(tmp_path, raw, sample_rate)
        result = register_and_process(tmp_path, recordings_dir, atten_lim_db=atten_lim_db)
        _index[result["recording_id"]] = {
            name: m["path"] for name, m in result["methods"].items()
        }
        # Strip absolute paths from the response -- callers use /audio/{id}/{method}.
        return {
            "recording_id": result["recording_id"],
            "duration_sec": result["duration_sec"],
            "methods": {name: {"dnsmos": m["dnsmos"]} for name, m in result["methods"].items()},
        }

    @app.get("/list")
    async def list_recordings():
        return {"recording_ids": sorted(_index.keys(), reverse=True)}

    @app.get("/audio/{recording_id}/{method}")
    async def audio(recording_id: str, method: str):
        entry = _index.get(recording_id)
        if entry is None or method not in entry:
            raise HTTPException(status_code=404,
                                 detail=f"no {method!r} recording for {recording_id!r}")
        path = entry[method]
        if not os.path.exists(path):
            raise HTTPException(status_code=404, detail="recording file missing on disk")
        return FileResponse(path, media_type="audio/wav")

    return app


# ---------------------------------------------------------------------------
# Self-test (Mode A -- no microphone, uses a synthetic clip written to disk)
# ---------------------------------------------------------------------------
def _self_test():
    print("demo/webdash/record_compare.py self-test -- start")
    import tempfile

    tmp_dir = tempfile.mkdtemp(prefix="record_compare_selftest_")
    try:
        sr = 48000
        t = np.arange(int(sr * 2.0)) / sr   # 2s synthetic clip (fast self-test)
        rng = np.random.default_rng(0)
        speech = 0.3 * np.sin(2 * np.pi * 300 * t)
        noisy = (speech + 0.2 * rng.standard_normal(len(t))).astype(np.float32)
        raw_path = os.path.join(tmp_dir, "raw.wav")
        sf.write(raw_path, noisy, sr)

        result = register_and_process(raw_path, recordings_dir=tmp_dir)
        assert result["recording_id"], "recording_id must be non-empty"
        assert set(result["methods"].keys()) == set(METHODS), (
            f"expected methods {METHODS}, got {list(result['methods'].keys())}"
        )
        print(f"  [PASS] test 1: register_and_process() ran all {len(METHODS)} methods "
              f"(noisy, spectral_subtraction, wiener, deepfilternet_tuned) on a synthetic clip")

        for name, m in result["methods"].items():
            assert os.path.exists(m["path"]) and os.path.getsize(m["path"]) > 0, (
                f"{name}: output file missing or empty"
            )
        print("  [PASS] test 2: every method's output WAV exists and is non-empty on disk")

        # DNSMOS is either a real result or None -- never silently fabricated.
        for name, m in result["methods"].items():
            d = m["dnsmos"]
            if d is not None:
                assert 1.0 <= d["sig"] <= 5.0 and 1.0 <= d["bak"] <= 5.0 and 1.0 <= d["ovr"] <= 5.0
        print("  [PASS] test 3: DNSMOS is either a real in-range score or None "
              "(never a fabricated placeholder)")

        assert "nlms" not in result["methods"], (
            "oracle NLMS must be excluded from record_compare -- no isolated noise "
            "reference exists for a live recording"
        )
        print("  [PASS] test 4: oracle NLMS baseline is correctly excluded "
              "(no isolated noise-only reference exists for a live recording)")

        if _FASTAPI_OK:
            from starlette.testclient import TestClient
            # record_clip() needs real microphone hardware, so /record itself
            # isn't exercised here -- this checks the /audio lookup's path
            # safety instead: an unregistered recording_id (this app instance
            # never POSTed to /record) must 404, not leak or crash, whether or
            # not that id happens to exist as a directory from another run.
            app = make_record_app(recordings_dir=tmp_dir)
            client = TestClient(app, raise_server_exceptions=True)
            r = client.get(f"/audio/{result['recording_id']}/noisy")
            assert r.status_code == 404, "unregistered recording_id must 404, never read straight off disk"
            r = client.get("/audio/not_a_real_id/noisy")
            assert r.status_code == 404
            print("  [PASS] test 5: /audio 404s for any recording_id this app instance didn't "
                  "itself register via /record -- lookup is index-based, never a raw path join")
    finally:
        import shutil
        shutil.rmtree(tmp_dir, ignore_errors=True)

    print("demo/webdash/record_compare.py self-test -- ALL PASSED")


if __name__ == "__main__":
    parser = argparse.ArgumentParser()
    parser.add_argument("--self-test", action="store_true")
    args = parser.parse_args()
    if args.self_test:
        _self_test()
    else:
        print("This module is a library. Use --self-test or import make_record_app.")
